name: learnsynth
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.0
  http: ^1.2.1
  permission_handler: ^11.3.0
  file_selector: ^1.0.3
  vosk_flutter: ^0.3.48
  syncfusion_flutter_pdf: ^25.2.7
  cupertino_icons: ^1.0.8
  ffmpeg_kit_flutter: ^4.5.1
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/vosk/model/
