version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - MAX_MEDIA_BYTES=104857600   # 100 MB
