version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env   
    environment:
    - LLM_PROVIDER=${LLM_PROVIDER:-anthropic}
    - LLM_FALLBACK_PROVIDER=${LLM_FALLBACK_PROVIDER:-openai}
    - OPENAI_API_KEY=${OPENAI_API_KEY}
    - OPENAI_MODEL=${OPENAI_MODEL}
    - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    - ANTHROPIC_MODEL=${ANTHROPIC_MODEL}
    - OPENAI_TRANSCRIBE_MODEL=${OPENAI_TRANSCRIBE_MODEL}
    - OPENAI_BASE_URL=https://api.openai.com/v1         # 100 MB
