version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - LLM_PROVIDER=${LLM_PROVIDER:-anthropic}
      - OPENAI_API_KEY=${OPENAI_API_KEY}          # read from host/.env at runtime
      - OPENAI_BASE_URL=https://api.openai.com/v1
      - OPENAI_TRANSCRIBE_MODEL=whisper-1
      - MAX_MEDIA_BYTES=104857600                 # 100 MB
